% DownloadContainerFilter
%
% DownloadContainerFilter Properties:
%    tags 
%
% DownloadContainerFilter Methods:
%    toJson - Convert the object to a Map that can be encoded to json
%    struct - Convert the object to a struct
    classdef DownloadContainerFilter < flywheel.ModelBase
    % NOTE: This file is auto generated by the swagger code generator program.
    % Do not edit the file manually.
    properties (Constant)
        propertyMap = containers.Map({ 'tags' }, ...
            { 'tags' });
    end
    properties(Dependent)
        tags
    end
    methods
        function obj = DownloadContainerFilter(varargin)
            obj@flywheel.ModelBase(flywheel.model.DownloadContainerFilter.propertyMap);

            % Allow empty object creation
            if length(varargin)
                p = inputParser;
                addParameter(p, 'tags', []);

                parse(p, varargin{:});

                if ~isempty(p.Results.tags)
                    obj.props_('tags') = p.Results.tags;
                end
            end
        end
        function result = get.tags(obj)
            if ismethod(obj, 'get_tags')
                result = obj.get_tags();
            else
                if isKey(obj.props_, 'tags')
                    result = obj.props_('tags');
                else
                    result = [];
                end
            end
        end
        function obj = set.tags(obj, value)
            obj.props_('tags') = value;
        end
        function result = toJson(obj)
            result = containers.Map;
            if isKey(obj.props_, 'tags')
                result('tags') = obj.props_('tags').toJson();
            end
        end
        function result = struct(obj)
            result = struct;

            if isKey(obj.props_, 'tags')
                result.tags = struct(obj.props_('tags'));
            else
                result.tags = [];
            end
        end
        function result = returnValue(obj)
            result = obj;
        end
    end
    methods(Access = protected)
        function prpgrp = getPropertyGroups(obj)
            if ~isscalar(obj)
                prpgrp = getPropertyGroups@matlab.mixin.CustomDisplay(obj);
            else
                propList = struct;
                if isKey(obj.props_, 'tags')
                    propList.tags = obj.props_('tags');
                else
                    propList.tags = [];
                end
                prpgrp = matlab.mixin.util.PropertyGroup(propList);
            end
        end
    end
    methods(Static)
        function obj = fromJson(json, context)
            obj =  flywheel.model.DownloadContainerFilter;
            if isfield(json, 'tags')
                obj.props_('tags') = flywheel.model.DownloadContainerFilterDefinition.fromJson(json.tags, context);
            end
            if isprop(obj, 'context_')
                obj.setContext_(context);
            end
        end
        function obj = ensureIsInstance(obj)
            if ~isempty(obj)
                % Realistically, we only convert structs
                if ~isa(obj, 'flywheel.model.DownloadContainerFilter')
                    obj = flywheel.model.DownloadContainerFilter(obj);
                end
                if isKey(obj.props_, 'tags')
                    obj.props_('tags') =  flywheel.model.DownloadContainerFilterDefinition.ensureIsInstance(obj.props_('tags'));
                end
            end
        end
    end
end
