% InlineResponse2003
%
% InlineResponse2003 Properties:
%    id       - Database ID of a user
%    roleIds 
%    access  
%
% InlineResponse2003 Methods:
%    toJson - Convert the object to a Map that can be encoded to json
%    struct - Convert the object to a struct
    classdef InlineResponse2003 < flywheel.ModelBase
    % NOTE: This file is auto generated by the swagger code generator program.
    % Do not edit the file manually.
    properties (Constant)
        propertyMap = containers.Map({ 'id', 'roleIds', 'access' }, ...
            { '_id', 'role_ids', 'access' });
    end
    properties(Dependent)
        id
        roleIds
        access
    end
    methods
        function obj = InlineResponse2003(varargin)
            obj@flywheel.ModelBase(flywheel.model.InlineResponse2003.propertyMap);

            % Allow empty object creation
            if length(varargin)
                p = inputParser;
                addParameter(p, 'id', []);
                addParameter(p, 'roleIds', []);
                addParameter(p, 'access', []);

                parse(p, varargin{:});

                if ~isempty(p.Results.id)
                    obj.props_('_id') = p.Results.id;
                end
                if ~isempty(p.Results.roleIds)
                    obj.props_('role_ids') = p.Results.roleIds;
                end
                if ~isempty(p.Results.access)
                    obj.props_('access') = p.Results.access;
                end
            end
        end
        function result = get.id(obj)
            if ismethod(obj, 'get_id')
                result = obj.get_id();
            else
                if isKey(obj.props_, '_id')
                    result = obj.props_('_id');
                else
                    result = [];
                end
            end
        end
        function obj = set.id(obj, value)
            obj.props_('_id') = value;
        end
        function result = get.roleIds(obj)
            if ismethod(obj, 'get_roleIds')
                result = obj.get_roleIds();
            else
                if isKey(obj.props_, 'role_ids')
                    result = obj.props_('role_ids');
                else
                    result = [];
                end
            end
        end
        function obj = set.roleIds(obj, value)
            obj.props_('role_ids') = value;
        end
        function result = get.access(obj)
            if ismethod(obj, 'get_access')
                result = obj.get_access();
            else
                if isKey(obj.props_, 'access')
                    result = obj.props_('access');
                else
                    result = [];
                end
            end
        end
        function obj = set.access(obj, value)
            obj.props_('access') = value;
        end
        function result = toJson(obj)
            result = containers.Map;
            if isKey(obj.props_, '_id')
                result('_id') = flywheel.ModelBase.serializeValue(obj.props_('_id'), 'char');
            end
            if isKey(obj.props_, 'role_ids')
                result('role_ids') = flywheel.ModelBase.serializeValue(obj.props_('role_ids'), 'vector[char]');
            end
            if isKey(obj.props_, 'access')
                result('access') = flywheel.ModelBase.serializeValue(obj.props_('access'), 'char');
            end
        end
        function result = struct(obj)
            result = struct;

            if isKey(obj.props_, '_id')
                result.id = obj.props_('_id');
            else
                result.id = [];
            end
            if isKey(obj.props_, 'role_ids')
                result.roleIds = obj.props_('role_ids');
            else
                result.roleIds = [];
            end
            if isKey(obj.props_, 'access')
                result.access = obj.props_('access');
            else
                result.access = [];
            end
        end
        function result = returnValue(obj)
            result = obj;
        end
    end
    methods(Access = protected)
        function prpgrp = getPropertyGroups(obj)
            if ~isscalar(obj)
                prpgrp = getPropertyGroups@matlab.mixin.CustomDisplay(obj);
            else
                propList = struct;
                if isKey(obj.props_, '_id')
                    propList.id = obj.props_('_id');
                else
                    propList.id = [];
                end
                if isKey(obj.props_, 'role_ids')
                    propList.roleIds = obj.props_('role_ids');
                else
                    propList.roleIds = [];
                end
                if isKey(obj.props_, 'access')
                    propList.access = obj.props_('access');
                else
                    propList.access = [];
                end
                prpgrp = matlab.mixin.util.PropertyGroup(propList);
            end
        end
    end
    methods(Static)
        function obj = fromJson(json, context)
            obj =  flywheel.model.InlineResponse2003;
            if isfield(json, 'x0x5Fid')
                obj.props_('_id') = flywheel.ModelBase.deserializeValue(json.x0x5Fid, 'char');
            end
            if isfield(json, 'role_ids')
                obj.props_('role_ids') = flywheel.ModelBase.deserializeValue(json.role_ids, 'vector[char]');
            end
            if isfield(json, 'access')
                obj.props_('access') = flywheel.ModelBase.deserializeValue(json.access, 'char');
            end
            if isprop(obj, 'context_')
                obj.setContext_(context);
            end
        end
        function obj = ensureIsInstance(obj)
            if ~isempty(obj)
                % Realistically, we only convert structs
                if ~isa(obj, 'flywheel.model.InlineResponse2003')
                    obj = flywheel.model.InlineResponse2003(obj);
                end
                if isKey(obj.props_, '_id')
                end
                if isKey(obj.props_, 'role_ids')
                end
                if isKey(obj.props_, 'access')
                end
            end
        end
    end
end
