% JobAskStateResponse - Return number of jobs for a given state and query
%
% JobAskStateResponse Properties:
%    count 
%
% JobAskStateResponse Methods:
%    toJson - Convert the object to a Map that can be encoded to json
%    struct - Convert the object to a struct
    classdef JobAskStateResponse < flywheel.ModelBase
    % NOTE: This file is auto generated by the swagger code generator program.
    % Do not edit the file manually.
    properties (Constant)
        propertyMap = containers.Map({ 'count' }, ...
            { 'count' });
    end
    properties(Dependent)
        count
    end
    methods
        function obj = JobAskStateResponse(varargin)
            obj@flywheel.ModelBase(flywheel.model.JobAskStateResponse.propertyMap);

            % Allow empty object creation
            if length(varargin)
                p = inputParser;
                addParameter(p, 'count', []);

                parse(p, varargin{:});

                if ~isempty(p.Results.count)
                    obj.props_('count') = p.Results.count;
                end
            end
        end
        function result = get.count(obj)
            if ismethod(obj, 'get_count')
                result = obj.get_count();
            else
                if isKey(obj.props_, 'count')
                    result = obj.props_('count');
                else
                    result = [];
                end
            end
        end
        function obj = set.count(obj, value)
            obj.props_('count') = value;
        end
        function result = toJson(obj)
            result = containers.Map;
            if isKey(obj.props_, 'count')
                result('count') = flywheel.ModelBase.serializeValue(obj.props_('count'), 'integer');
            end
        end
        function result = struct(obj)
            result = struct;

            if isKey(obj.props_, 'count')
                result.count = obj.props_('count');
            else
                result.count = [];
            end
        end
        function result = returnValue(obj)
            result = obj;
        end
    end
    methods(Access = protected)
        function prpgrp = getPropertyGroups(obj)
            if ~isscalar(obj)
                prpgrp = getPropertyGroups@matlab.mixin.CustomDisplay(obj);
            else
                propList = struct;
                if isKey(obj.props_, 'count')
                    propList.count = obj.props_('count');
                else
                    propList.count = [];
                end
                prpgrp = matlab.mixin.util.PropertyGroup(propList);
            end
        end
    end
    methods(Static)
        function obj = fromJson(json, context)
            obj =  flywheel.model.JobAskStateResponse;
            if isfield(json, 'count')
                obj.props_('count') = flywheel.ModelBase.deserializeValue(json.count, 'integer');
            end
            if isprop(obj, 'context_')
                obj.setContext_(context);
            end
        end
        function obj = ensureIsInstance(obj)
            if ~isempty(obj)
                % Realistically, we only convert structs
                if ~isa(obj, 'flywheel.model.JobAskStateResponse')
                    obj = flywheel.model.JobAskStateResponse(obj);
                end
                if isKey(obj.props_, 'count')
                end
            end
        end
    end
end
