%% Create Matlab files with the labels, values, and common
%
% We set the full labels, shorthand, and most common labels here.
% We then use stSetLabels.m to upload the relevant labels to a
% project.
%
% See also
%   s_fwoLabels (ophthalmology)

fname = fullfile(stRootPath,'local','stLabels.mat');

%% OCT Labels
oct.labels = {'No label',...
    'Internal LM', ...   % 1
    'Posterior vitreous' ...
    'Preretinal space',...        % 3
    'Nerve fiber layer',...       % 4
    'Ganglion cell layer', ...
    'Inner plexiform layer', ...  % 6
    'Inner nuclear layer', ...
    'Outer plexiform layer', ...
    'Henle fiber layer',...       % 9
    'Outer nuclear layer', ...
    'Outer segments', ...
    'External LM', ...            % 12
    'Myoid zone', ...
    'Ellipsoid Zone', ...
    'RPE', ...                    % 15
    'Choriocapillaris', ...
    'Choroid sclera junction', ...
    'Interdigitation zone',...
    'Fovea'};                     % 19

oct.values = {'N/A',...
    'ILM', ...
    'PCV' ...
    'PRS',...
    'NFL',...
    'GCL', ...
    'IPL', ...
    'INL', ...
    'OPL', ...
    'HFL',...
    'ONL', ...
    'OS', ...
    'ELM', ...
    'MZ', ...
    'EZ', ...
    'RPE', ...
    'CC', ...
    'CSH', ...
    'IZ', ...
    'FOV'};

oct.common = [1 2 4 6 12 15 19];

assert(numel(oct.values) == numel(oct.labels))

save(fname,'oct');

%% Fundus labels

fundus.labels = {'Vessel', ...   
    'Optic nerve',...       
    'Fovea'};               

fundus.values = {'BV', ...
    'ON',...
    'FOV'}; 

fundus.common = [1 2 3];

assert(numel(fundus.values) == numel(fundus.labels))
save(fname,'fundus','-append');


%% Cortex labels

cortex.labels = {'White', ...   
    'Gray' ...
    'V1',...          
    'V2',...       
    'Calcarine',...
    'Optic chiasm',...
    'Optic nerve'};

cortex.values = {'WHT', ...
    'GRY' ...
    'V1',...
    'V2',...
    'Calc',...
    'OC', ...
    'ON'}; 

cortex.common = [1 2 3 4 5];

assert(numel(cortex.values) == numel(cortex.labels))

save(fname,'cortex','-append');

%%
